#!/usr/bin/env bash

VMRSS=$VMRSS ./collect
./cpy_parse processed/data processed/totals
./concat processed/totals processed/concat
./csv processed/concat processed/output.csv
./graph processed/output.csv
